
pool:
  vmImage: 'windows-latest'
  name: 'Agentes_Compilacion'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 1
  minor: 0
  NUGET_ENABLE_LEGACY_CSPROJ_PACK: true

name: $(major).$(minor)$(Rev:.rr)

steps:
# 1. Instalar NuGet
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

# 3. Restauración
- task: NuGetCommand@2
  displayName: 'Restore packages from internal feed'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    vstsFeed: '80c17264-11a0-4f4d-98e0-86e0e5e465ce/90471a02-3bf6-420e-8a67-8ac2f550d3c1'
    noCache: true

# 4. Compilación
- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
# 5. Publicación en feed
- task: DotNetCoreCLI@2
  displayName: 'Push Yape-Library-Soap-Client'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/Yape-Library-Soap-Client.*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '80c17264-11a0-4f4d-98e0-86e0e5e465ce/90471a02-3bf6-420e-8a67-8ac2f550d3c1'