<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
	  <RootNamespace>GK.Library.Soap.Client</RootNamespace>
    <AssemblyName>GK.Library.Soap.Client</AssemblyName>
    <PackageId>GK.Library.Soap.Client</PackageId>
	  <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
	  <PackageDescription>
		  Cliente SOAP para .NET 8 con retries Polly, logging y extensión de DI; expone un puerto para consumir servicios WCF.
	  </PackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.7" />
    <PackageReference Include="Polly" Version="8.6.2" />
    <PackageReference Include="System.ServiceModel.Http" Version="8.1.2" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="8.1.2" />
  </ItemGroup>

</Project>
